// <auto-generated />
using System;
using DataLayer.EF.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLayer.Migrations.PalletMigration
{
    [DbContext(typeof(PalletContext))]
    partial class PalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models.Entities.Pallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<bool>("InUse")
                        .HasColumnType("bit")
                        .HasColumnName("InUse");

                    b.Property<int>("MaxHeight")
                        .HasColumnType("int")
                        .HasColumnName("MaxHeight");

                    b.Property<int>("MaxWeight")
                        .HasColumnType("int")
                        .HasColumnName("MaxWeight");

                    b.Property<int>("OverReach")
                        .HasColumnType("int")
                        .HasColumnName("OverReach");

                    b.Property<string>("PalletGroup")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PalletGroup");

                    b.Property<string>("PalletMaterial")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("PalletMaterial");

                    b.Property<int>("SpaceBetween")
                        .HasColumnType("int")
                        .HasColumnName("SpaceBetween");

                    b.Property<bool>("SpecialCargo")
                        .HasColumnType("bit")
                        .HasColumnName("SpecialCargo");

                    b.Property<int>("Spots")
                        .HasColumnType("int")
                        .HasColumnName("Spots");

                    b.Property<int>("Weight")
                        .HasColumnType("int")
                        .HasColumnName("Weight");

                    b.HasKey("Id");

                    b.ToTable("Pallets", (string)null);
                });

            modelBuilder.Entity("Models.Entities.Pallet", b =>
                {
                    b.OwnsOne("Models.Common.Dimensions3D", "Dimensions", b1 =>
                        {
                            b1.Property<Guid>("PalletId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("X")
                                .HasColumnType("int")
                                .HasColumnName("Width");

                            b1.Property<int>("Y")
                                .HasColumnType("int")
                                .HasColumnName("Height");

                            b1.Property<int>("Z")
                                .HasColumnType("int")
                                .HasColumnName("Depth");

                            b1.HasKey("PalletId");

                            b1.ToTable("Pallets");

                            b1.WithOwner()
                                .HasForeignKey("PalletId");
                        });

                    b.Navigation("Dimensions")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
